# Generated by Django 4.1.1 on 2022-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
