# Generated by Django 4.1.1 on 2022-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='entrada',
            field=models.BooleanField(default=False),
        ),
    ]
