# Generated by Django 4.1.1 on 2022-10-08 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='llavero',
        ),
        migrations.AddField(
            model_name='llavero',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.estudiante'),
        ),
    ]
