# Generated by Django 4.1.1 on 2022-10-07 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_estudiante_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.materia'),
        ),
    ]
