# Generated by Django 4.1.1 on 2022-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_estudiante_llavero_llavero_estudiante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llavero',
            old_name='llavero',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='llavero',
            old_name='llavero_status',
            new_name='tag_status',
        ),
    ]
