# Generated by Django 4.1.1 on 2022-10-06 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula', models.CharField(max_length=50)),
                ('llavero', models.CharField(max_length=45, unique=True)),
                ('llavero_status', models.BooleanField(default=False)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('materias', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.materia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('numero', models.CharField(max_length=50)),
                ('sede', models.CharField(choices=[('Sede San Camilo', 'Sede San Camilo'), ('Sede San Jose', 'Sede San Jose')], default='Sede San Jose', max_length=50)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('estudiantes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.estudiante')),
                ('materia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.materia')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profesor')),
            ],
        ),
    ]
