# Generated by Django 4.1.1 on 2022-10-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_estudiante_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('asistencia', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.asistencia')),
            ],
        ),
    ]
